# Generated by Django 4.1.1 on 2023-05-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_langs_alter_comment_snippet_alter_snippet_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='lang',
        ),
    ]
