# Generated by Django 4.1.1 on 2023-05-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_remove_snippet_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.langs'),
        ),
    ]
