# Generated by Django 4.1.1 on 2023-05-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_snippet_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='lang',
        ),
    ]
